### ISSUE TITLE
Provide coyim as Flatpak

### ISSUE THREAD

**Issue by yurkobb** [coyim/coyim#488] opened 2018-03-05 10:06 UTC
Currently the cross-distro variant of coyim is a binary, which is not bad, but I have to fully trust it if I want to run it.

Flatpak, on the other hand, provides a built-in sandbox, which means that I can install and run coyim without exposing the contents of my home directory (and other possibly sensitive filesystem locations) to it.

**Comment by olabini** [comment] 2018-03-05 10:08
Actually, you don't have to fully trust it. You don't have to trust it at all - since you can build the binary reproducibly and verify the source code.

This is also a duplicate of #429 - so I'll close this. If you want to add something about this situation, please do it to #429 instead! =)

**Closed by olabini** 2018-03-05 10:08 UTC

**Comment by yurkobb** [comment] 2018-03-05 10:10
Sorry, I searched and couldn't find the other issue.
