### ISSUE TITLE
Button frozen when mouse hover

### ISSUE THREAD

**Issue by blackbnu** [coyim/coyim#189] opened 2015-12-17 02:50 UTC
Using V0.1 for OS X Yosemite 10.10.5

**Comment by juniorz** [comment] 2015-12-17 03:10
Try CTRL+V

**Comment by blackbnu** [comment] 2015-12-17 03:16
CTRL+V works... completely counter intuitive though.
I also tried Right Button + Paste and it didn't work.

**Comment by olabini** [comment] 2015-12-17 13:47
Right button + paste didn't work? That's strange.
We definitely need to get the keys right for OS X

**Comment by olabini** [comment] 2016-01-21 15:52
This is also connected with #31

**Comment by tcz001** [comment] 2016-01-27 22:05
Cmd+V on Mac should be fixed by 4c8a592cc7e38936f2a14009c0e6dfe4389bbcf6

Right Button+Paste is behaving strange because some GTK+'s Quartz button frozen problem, changing the title.

**Comment by olabini** [comment] 2016-01-28 17:06
Any idea on what causes this?

**Comment by olabini** [comment] 2016-01-28 17:24
This might be a helpful workaround: https://mail.gnome.org/archives/gtk-app-devel-list/2015-March/msg00027.html

**Comment by tcz001** [comment] 2016-02-02 21:26
I can't reproduce this after upgrade to El Capitan, WTF?

**Comment by juniorz** [comment] 2016-02-02 22:42
Fixed with a CSS change:

```
$ cat ~/.config/gtk-3.0/gtk.css
.context-menu {
  margin: 0;
}
```

**Comment by juniorz** [comment] 2016-02-02 23:08
There is something specific to our GTK app.

The previous comment fix `gtk3-demo` but has no effect on `coy`. I suspect there is something on the way we initialize the GTK environment that prevents `coy` from loading `~/.config/gtk-3.0/gtk.css` in this case.

**Comment by juniorz** [comment] 2016-02-02 23:17
And adding this CSS rules to the same file that fixes the CMD+V shortcut does not work.

**Comment by juniorz** [comment] 2016-02-02 23:32
From GTK documentation:

> In addition, certain files will be read when GTK+ is initialized. First, the file $XDG_CONFIG_HOME/gtk-3.0/gtk.css is loaded if it exists. Then, GTK+ tries to load $HOME/.themes/theme-name/gtk-3.0/gtk.css, falling back to datadir/share/themes/theme-name/gtk-3.0/gtk.css, where theme-name is the name of the current theme (see the “gtk-theme-name” setting) and datadir is the prefix configured when GTK+ was compiled, unless overridden by the GTK_DATA_PREFIX environment variable.

https://developer.gnome.org/gtk3/stable/GtkCssProvider.html

So we added the following to the wrapper:

`export XDG_CONFIG_HOME="$bundle_etc"`

And added the file `gtk.css` with the changes to `Contents/Resources/etc/gtk-3.0/`

Then it works with a small caveat: the configuration file is loaded from the same `XDG_CONFIG_HOME` :(

Let's try to load it from `datadir/share/themes/theme-name/gtk-3.0/gtk.css`

**Comment by juniorz** [comment] 2016-02-03 01:03
This is actually the CSS that fixes the issue and, yes it has effect on both `coy` and `gtk3-demo` apps.

```
* > GtkMenu {
  margin: 0;
}
```

The problem was the previous CSS only changed the context menu, and we were using the account popup menu (which are NOT the same thing). Context menu is only the OS thing with "copy", "paste", and whatever.

**Comment by juniorz** [comment] 2016-02-03 01:17
Now we need to figure out where to put this file. We can not trust in how the `gtk-keys.css` works because it is a special case: https://developer.gnome.org/gtk3/stable/gtk-migrating-GtkStyleContext.html

**Comment by tcz001** [comment] 2016-02-03 14:10
I'm doubting how Mac theme can be chosen while Awaita is in setting.ini. :(

**Comment by tcz001** [comment] 2016-09-25 03:38
This appears again in recent UX meeting with @SweetVirginia , reopen.

**Comment by olabini** [comment] 2016-11-08 19:39
Have you been able to investigate this?

**Comment by olabini** [comment] 2016-12-20 15:15
Any news here?

**Comment by olabini** [comment] 2019-02-13 17:25
This was fixed a while back with some other changes.

**Closed by olabini** 2019-02-13 17:25 UTC
Labels: bug
