### ISSUE TITLE
I have a problem about registration

### ISSUE THREAD

**Issue by s3pt3mb3r** [coyim/coyim#496] opened 2018-06-22 18:25 UTC
![image](https://user-images.githubusercontent.com/33578715/41792735-6cefa1c4-768c-11e8-8530-46a1fe850e16.png)

This is screen shot of registration window.
When I fill in the server name and click Next, coy will crash.

**Comment by olabini** [comment] 2018-08-20 14:39
We need a little bit more information for us to be able to debug this. What does it say when crashing? Any output from the command line? What operating system?

**Comment by olabini** [comment] 2018-08-20 14:58
Ah, it turns out this issue is a duplicate of #438 and has been fixed on trunk.

**Closed by olabini** 2018-08-20 14:58 UTC

**Comment by grrrrr** [comment] 2018-09-24 16:47
@olabini  any plans for a bug fix release? This ticket (#496) was submitted just short of a year after the issue was fixed in #438
