### ISSUE TITLE
Deny entering a room where you are banned with an appropriate message (7.2.7)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#590] opened 2020-07-20 14:55 UTC
If you are banned from a room, when trying to enter it you should be denied with a proper message.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment] 2020-07-22 15:00
This is part of #271.

**Comment by MauroVelasco** [comment] 2020-12-03 21:26
Ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment] 2020-12-04 17:42
Good enough. There's a small language issue in one comment, but nothing major.

**Comment by olabiniV2** [comment] 2020-12-09 15:13
OK

**Comment by peterpalau** [comment] 2020-12-09 16:54
This issue is done and ready to be closed.

**Comment by peterpalau** [comment] 2020-12-14 15:04
We were to fast closing this issue because there is a pending comment to fix, so I'm going to open it again to fix that comment.

**Comment by peterpalau** [comment] 2020-12-14 15:22
No more comments about things to fix. The issue is ready to be closed.

**Closed by peterpalau** 2020-12-14 15:22 UTC
Labels: Estimate - small, MUC, MUC - Rooms Permissions to access Functionality, Priority: Now, State: Done
