### ISSUE TITLE
Add the items to the banned occupant list in the same order as the add dialog.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#769] opened 2021-08-16 19:51 UTC

**Comment by peterpalau** [comment] 2021-08-17 14:47
The issue is ready for user testing.

**Comment by olabiniV2** [comment] 2021-08-31 21:05
The resolution for one of the code review comments haven't been tagged for this issue, so it can be tracked...
Not accepted.

**Comment by IvanJijon** [comment] 2021-08-31 21:55
> The resolution for one of the code review comments haven't been tagged for this issue, so it can be tracked...
> Not accepted.

The comment has been fixed in commit 30c8dd1.

**Comment by azlancpool** [comment] 2021-09-01 14:32
So all comments were replied, it's ready to be reviewed

**Comment by azlancpool** [comment] 2021-09-01 15:45
First we need to do user-test instead of code-review

**Comment by olabiniV2** [comment] 2021-09-02 22:06
OK

**Closed** 2021-09-03 14:13 UTC
Labels: MUC, State: Done
