### ISSUE TITLE
Show the list of services available on the server in the join the room functionality

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#672] opened 2020-11-09 19:01 UTC

**Comment by olabiniV2** [comment] 2020-11-09 21:25
We want to be consistent everywhere a user can input a room name. That means we should follow the design which is in the "Create room" dialog, where we have one input box for the local name, and another box which is a dropdown of available services for the user, AND the possibility of writing another service name as well.

**Comment by MauroVelasco** [comment] 2020-11-09 22:10
Currently, we improve the join window adding the dropdown component for chat services information solving this issue but, we noticed that there are commons fields and functionalities for the create and join a room windows generating code duplication. We think that we could improve this, handling a single form for both cases.

**Comment by Cris2760** [comment] 2020-11-11 17:19
Ready for @olabiniV2 review

**Comment by olabiniV2** [comment] 2020-11-11 18:44
There are some comments in the code that should be resolved before this is done. Obviously, it should also be user tested.

**Comment by peterpalau** [comment] 2020-11-11 18:52
> There are some comments in the code that should be resolved before this is done. Obviously, it should also be user tested.

We, @MauroVelasco and I have reviewed the comments and I they are fixed.
Just one related to your question in https://github.com/coyim/coyim/commit/30ec4370706db94fa0ae37c824d5074fd5c50257#r44089493: 

> Are these long field names useful?

We think they are okay because they help us (from our point of view) to understand the code in a better way but, maybe we can call it in a simple way, like for example instead of `chatServicesBox gtki.Box` use `box gtki.Box`. Is that okay for you @olabini?

Apart of that we can't find any other pending comment.

**Comment by peterpalau** [comment] 2020-11-11 19:01
Okay we did an update and the fields were updated to the following:

```
servicesList    gtki.ComboBoxText
serviceEntry    gtki.Entry
```

With this fixes we think we are ready to do user testing.

**Comment by olabiniV2** [comment] 2020-11-12 18:00
OK, looks good! I'll close this. Thanks.

**Comment by olabiniV2** [comment] 2020-11-12 18:01
Actually, I was too fast. I'm not sure if this has been user tested or not, so let's keep it open until we know.

**Comment by olabiniV2** [comment] 2020-11-19 16:14
OK, I've looked at the last commit - some things to fix here.

**Comment by peterpalau** [comment] 2020-11-20 22:06
The comments has been fixed, this issue is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment] 2020-11-23 20:59
OK, I've added some comments. There are still some things that need to be fixed for this story.

**Comment by peterpalau** [comment] 2020-11-24 16:44
Okay, all the comments has been fixed.

**Comment by olabiniV2** [comment] 2020-11-24 18:22
OK, looks good.

**Comment by peterpalau** [comment] 2020-11-24 18:42
The issue is done.

**Closed by peterpalau** 2020-11-24 18:42 UTC
Labels: MUC, Priority: Now, State: Test, bug
