### ISSUE TITLE
Highlight the name of the user and the role in the different messages.

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#704] opened 2021-03-03 20:23 UTC
Such as in "An error occurred trying to change the role of test to moderator". In this message, the words "test" and "moderator" both seem like they're the same as the rest of the sentence. Do not use quotes or other orthographic signs, since they have specific meaning. Instead, we should think about things like italic or bold or something like that.

**Comment by peterpalau** [comment] 2021-04-09 19:46
Talking with @Cris2760 we realized this issue requires a major effort and right now it's not a priority. For that reason, we decided to move it again to Ready.

**Comment by peterpalau** [comment] 2021-07-20 12:30
We need to highlight the nickname and the other things in the conversation view too.

**Comment by peterpalau** [comment] 2021-07-20 20:18
The text highlighting in the conversation view is ready. The issue is ready to be reviewed in the user testing.

**Comment by olabiniV2** [comment] 2021-08-03 15:00
Reviewed, looks good to me. Except, I'm not happy at all that someone did a force push...

Also, it would be good if we can do a pull request of the pango attributes stuff and related things to `gotk3` now that we are up to HEAD of gotk3 again.

**Comment by peterpalau** [comment] 2021-08-04 15:04
> Also, it would be good if we can do a pull request of the pango attributes stuff and related things to gotk3 now that we are up to HEAD of gotk3 again.

Aha, we should. This issue is going back to doing.

**Comment by peterpalau** [comment] 2021-08-04 18:32
The pull request is available via https://github.com/gotk3/gotk3/pull/821.
Once the gotk3 team accepts it, we should adapt all the changes into our packages.

**Comment by peterpalau** [comment] 2021-08-10 14:32
Okay, the PR was merged. We should update our code to use that updated.

**Comment by peterpalau** [comment] 2021-08-16 14:44
After the first merge, we found more problems in how lists are freed in gotk3.
We did another PR via https://github.com/gotk3/gotk3/pull/824 to fix this problem.

**Comment by olabiniV2** [comment] 2021-08-19 18:20
This one still seems to have open code review comments, so not accepted.

**Comment by olabiniV2** [comment] 2021-08-31 20:58
OK

**Closed** 2021-08-31 21:06 UTC
Labels: MUC, Priority: Soon, State: Done
