### ISSUE TITLE
Failing Test_openLogFile_failsIfCantOpenFile

### ISSUE THREAD

**Issue by sacurio** [coyim/coyim#728] opened 2021-03-10 15:07 UTC
The test is failing in Windows with the following output:

```
session_log_test.go:39:
    c.Assert(hook.LastEntry().Data["error"], ErrorMatches, ".*not a directory")
... error string = "open C:\\Users\\cad\\AppData\\Local\\Temp\\226351666\\something elsE: The system cannot find the path specified."
... regex string = ".*not a directory"
```

**Comment by olabiniV2** [comment] 2021-03-10 16:55
I think this commit solves the problem, but it should be verified before we close the issue.

**Comment by peterpalau** [comment] 2021-03-11 15:59
We tested the fix in Windows and is working.

**Comment by peterpalau** [comment] 2021-03-11 15:59
The issue is ready to be closed.

**Closed by peterpalau** 2021-03-11 15:59 UTC
Labels: State: Done, windows
