### ISSUE TITLE
Minimize button does not work on Mac

### ISSUE THREAD

**Issue by claucece** [coyim/coyim#458] opened 2017-10-26 05:38 UTC
Currently, the minimize button of main window does nothing on Mac. Maximize and close buttons seem to work fine.

**Comment by claucece** [comment] 2017-11-10 00:29
As seen in commit 24e2a651353cfcb1b82ed96cb006563e1897a954, creating our own minimize button, still gives the same behavior. This can be related, then, with 'gtk_window_iconify' or it not recognizing a window manager.

**Comment by olabini** [comment] 2018-08-20 15:38
Is this still an issue? Any idea what the appropriate fix is?

**Comment by claucece** [comment] 2018-08-20 15:40
Yeah, it is still an issue. Well, looking at the window manager to see if it recognizes it.

**Comment by olabiniV2** [comment] 2020-06-07 13:34
This has been fixed in the last commit. The problem was that by setting the TitleBar, we turned off native client side decorations on OS X. That, combined with a bug in gdk-quartz that doesn't make it possible to minimize undecorated windows, was the cause for this problem. By not setting the title bar, we will use the native controls on Mac OS X.

**Closed by olabiniV2** 2020-06-07 13:34 UTC
Labels: bug, os x
