### ISSUE TITLE
Destroy a room (10.9)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#656] opened 2020-07-20 16:51 UTC
This functionality allows an owner to destroy a room they are in. The destruction can take an optional reason, an optional alternative room, and an optional password for this alternative room. 

After the destruction, the room view should display in the same way as described as in #657 - except there should be an option for the owner to have the room view window be closed directly after the destruction.

If the destruction fails, a notification should be shown to the owner - probably _not_ in the conversation view, but somewhere else.

(should we have a different functionality for destroying a room you're not currently in? Is that even possible?)

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment] 2020-07-21 22:02
This is part of #271.

**Comment by peterpalau** [comment] 2020-11-19 16:01
This issue is ready to be reviewed by @olabini

**Comment by olabiniV2** [comment] 2020-11-19 17:06
OK, so there are a bunch of comments to review before this story is done!

**Comment by peterpalau** [comment] 2020-11-19 21:41
@azlancpool and @peterpalau reviewed all the comments and, everything has been fixed, except the comment related with the hard code styles that will be part of a more global solution that will be doing in the next days.

Having said that, everything related to the context of this issue has been solved.

**Comment by olabiniV2** [comment] 2020-11-23 20:52
I've added some new comments.

**Comment by sacurio** [comment] 2020-11-24 16:58
All the comments has been fixed and the issue is ready to be reviewed by @olabiniV2 .

**Comment by olabiniV2** [comment] 2020-11-24 18:08
Some more comments.

**Comment by peterpalau** [comment] 2020-12-01 17:08
All the pending comments has been fixed, the issue is ready to be reviewed by @olabiniV2.

**Comment by peterpalau** [comment] 2020-12-01 20:17
Okay after a meeting with @olabiniV2 we decided this issue is not finished yet.

**Comment by azlancpool** [comment] 2020-12-02 21:49
We worked in the comments, this is ready to be reviewed by @olabiniV2

**Comment by olabiniV2** [comment] 2020-12-04 18:05
OK, so I've reviewed the code and left some comments. I've also looked at `session/muc_room_destroy.go` in its entirety again. And I'm still confused. Why is it so complicated? There's a bunch of stuff that just doesn't make sense. Things like, why are you saving `destroyRoomRequest` at all, when you never actually look them up, except to get the result and error channels - which could be done cleaner some other way. In fact, that could cause problems - if someone destroys the room two times, they will get the _same_ channels. That means that one of those two GUI threads will be waiting forever!

Also, what's the point of having fields for onDestroySuccess and onDestroyFinish, when they are hard coded anyway, and we don't see any reasonable situation where they will change?

Overall, this is still overengineered, unsafe and not clearly thought out.

**Comment by peterpalau** [comment] 2020-12-14 20:50
After our discussion with the team we came with a newer and simple solution for destroying a room.

**Comment by peterpalau** [comment] 2020-12-14 20:52
The issue is ready to be reviewed by @olabiniV2

**Comment by peterpalau** [comment] 2020-12-14 20:58
While we await the results of the code review, we will advance the user tests.

**Comment by olabiniV2** [comment] 2020-12-18 20:17
OK, there are some comments that need fixing, but except for that it's all good - I think the currently implementation is significantly simpler and better. This is done, once the small issues have been fixed.

**Comment by azlancpool** [comment] 2020-12-21 22:22
Some little fixes specified in comments were solved and we add some changes after the user tests.

**Comment by olabiniV2** [comment] 2020-12-22 15:59
OK, there are some new comments that still need to be fixed.

**Comment by sacurio** [comment] 2020-12-22 16:51
> OK, there are some new comments that still need to be fixed.

@olabiniV2 the issue is ready to be reviewed

**Comment by olabiniV2** [comment] 2020-12-28 17:13
OK, looks good to me now, it can be closed.

**Closed** 2020-12-28 17:25 UTC
Labels: Estimate - medium, MUC, MUC - Room Owner Capabilities Functionality, Priority: Now, State: Done
