### ISSUE TITLE
Unpredictable crash in various parts of the application

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#757] opened 2021-07-15 17:33 UTC

**Comment by olabiniV2** [comment] 2021-07-20 17:55
Our best guess is that this is the root cause of the problem: https://github.com/gotk3/gotk3/issues/810
However, the next step will be to try to provoke it to happen more often with `runtime.GC()` and then see what happens.

**Comment by olabiniV2** [comment] 2021-07-30 22:06
I'll take point on this.

**Comment by olabiniV2** [comment] 2021-07-31 20:23
This commit: c0a145bd35f8b441751f42c71cf3cf43d3f18af6 is very likely going to fix this problem. I'll ask @azlancpool to double-check on Monday.

**Comment by olabiniV2** [comment] 2021-08-03 14:19
So, @azlancpool ran a full day with the forced GC and we didn't see the crash at all. I consider this bug fixed with this evidence.

**Closed** 2021-08-03 14:19 UTC
Labels: MUC, State: Done, bug
