### ISSUE TITLE
Accounts dont show up after i close and open CoyIM

### ISSUE THREAD

**Issue by AlexIsNice** [coyim/coyim#528] opened 2019-04-25 06:01 UTC
Hello,so i add all my 3 XMPP Accounts,i close and then open CoyIM and only 1 is left when i reopen it.The really weird thing is that in my accounts.json all my accounts are there,and if i try to readd it i get that this account is already added but i cant see/connect to it.

Any tips?

Thank you!

**Comment by claucece** [comment] 2019-05-20 00:51
Mmm.. this is very difficult to actually see what is happening. Can you add some screenshots? Also, what OS are you using and are you using the latest release of CoyIM? Anything that shows up if you run with the debug flag?

Thanks!

**Comment by claucece** [comment] 2019-06-06 22:30
Hey @AlexIsNice .. any more info?

**Comment by claucece** [comment] 2019-06-10 20:45
I'm closing this issue due to lack of info.

**Comment by meme-lord** [comment] 2020-08-09 15:30
This issue exists in v0.3.11 on Windows . It only shows the first account in the accounts.json file when I reopen it.
It was working with multiple accounts when I had added them but they disappear when I reopen so it must be something to do with the way it loads the accounts.json file. Is this fixed on the current git version?

**Comment by olabiniV2** [comment] 2020-08-11 16:11
Hi,

Thank you for the request - that is very strange indeed. I have never seen this behavior. It would be very helpful if you could try to duplicate this issue, and run CoyIM with the debug flag (you do this by navigating to wherever CoyIM is located on the machine and running `coyim.exe -debug`). It would also be helpful if you can look inside the `accounts.json` file and see if all the different accounts are there.

**Comment by meme-lord** [comment] 2020-08-11 22:30
My accounts are in the accounts.json file. If I close it and open it sometimes I get two accounts, sometimes I get one account (there should be 6) . It's always the first two accounts. If I reorder accounts in the file it's still either the first one or the first two. I've tried launching with the debug flag but it does nothing, I set a log file in the settings but it is always empty.
It is easy for me to duplicate as it always happens, it seems it never loads all the accounts when I open it. I will try removing accounts from the list to see if maybe one particular account is causing a problem?

**Comment by meme-lord** [comment] 2020-08-11 22:38
So I've reduced the number of entries in the accounts.json file to two and the problem happens even when I swap the two out with other accounts so its not account specific.

**Comment by olabiniV2** [comment] 2020-08-12 17:53
Wow, that's extremely strange. You don't get any output at all when passing the debug flag? That shouldn't happen - even older versions of coy will write some debug output when it loads the configuration file and the accounts. This will just be written to the console where you started Coy with the debug flag. It would be super helpful if you could manage to get that output for us.

**Comment by meme-lord** [comment] 2020-08-12 17:59
Okay it does show the debug messages in gitbash but not in cmd.
```
GLib-GIO-Message: 18:57:03.455: gregistrybackend: error enumerating subkeys for cache.: More data is available.
[CoyIM] 2020/08/12 18:57:06 c:/gopath/src/github.com/coyim/coyim/config/account.go:166: [my@redacted.xmpp] ensureConfigHasKey()
[CoyIM] 2020/08/12 18:57:06 c:/gopath/src/github.com/coyim/coyim/session/session_log.go:17: Logging XMPP messages to: coyim_debug_log
[CoyIM] 2020/08/12 18:57:06 c:/gopath/src/github.com/coyim/coyim/session/session.go:101: Loading 1 configured keys
[CoyIM] 2020/08/12 18:57:06 c:/gopath/src/github.com/coyim/coyim/session/session.go:106: Loaded key: DEADBEEF DEADBEEF DEADBEEF DEADBEEF DEADBEEF
```
That is all the output from launching it.

**Comment by olabiniV2** [comment] 2020-08-12 18:07
Thank you, that's still very confusing! It doesn't tell us anything helpful, sadly. 
Do you think it would be possible to copy the configuration file here (redacting your JID, password all key information of course). You can also mail it to ola [at] olabini [dot] se - if that is more comfortable for you.

**Comment by meme-lord** [comment] 2020-08-12 18:14
I registered 2 new xmpp accounts for the purposes of this issue and reproduced the issue with this config.
```
{
	"Accounts": [
		{
			"Account": "thisisforcoyimtest@jabber.otr.im",
			"Proxies": [
				"tor-auto://"
			],
			"Password": "thisisforcoyimtest",
			"PrivateKeys": [
				"AAAAAACArkcK6XyRUlM3FdsD/aENDO27tqXnDbHsn8t8ASuDz3Go8+xt1of2bfUxVxQXZjdjtJiYQKC/sYvvxRb/QkhttsLMyfQ2FMS5Ycl2YlubHK0j2fvwdRiDateIpAVzA9uBLw8AszyXpTNS6bgNNlwq9qrmaN/T+EoRjY/zb2/yOsMAAAAU9unSJxwPr+eMvEPyGMZ/Mwg3s48AAACAYkToGYAFwqhFLn/PS2XYfQ/kZEv6xslqDB22wvUCUxR55quTeMqA8F8UQBwfwuIXANSYl17dbNF7zaa0PiKQH4NqKQUqR8mFK/lndanXCn2mcslrDo1Wn3lP0zMalQtK0Q71eRzFVSuLvsXvVsvbYt9Oj1yqEl0PN/XhECbWWYwAAACAZimy9YiO/TLvJgipNac4w3XUEd8NcxdowkVl5E2WZXDUuyy0bhL2ls2t7zuQ2RQr7Mj0udGEK2dpjK1OE1h1YTSSnRXzyoBZo2khoE4SawtYL37fwsMr6lKSrAUWa6BxCGi5jkOvyxexOL0nwWvCbl93AJ1x5uWhzU+n8DvrEjYAAAAUHuXBOn7U0WT+PIhLmL+SIeabzr4="
			],
			"Peers": null,
			"HideStatusUpdates": false,
			"OTRAutoTearDown": true,
			"OTRAutoAppendTag": true,
			"OTRAutoStartSession": true,
			"AlwaysEncrypt": true,
			"ConnectAutomatically": false,
			"Certificates": [
				{
					"Subject": "jabber.otr.im",
					"Issuer": "Let's Encrypt Authority X3",
					"FingerprintHex": "540d81f9612eb581b7f68a8ced4e3aa8d820ede6c132e8f20257cbb1d46d282d",
					"FingerprintType": "SHA3-256"
				}
			]
		},
		{
			"Account": "thisisforcoyimtest2@jabber.otr.im",
			"Proxies": [
				"tor-auto://"
			],
			"Password": "thisisforcoyimtest2",
			"PrivateKeys": [
				"AAAAAACAlpVPjlYeDy/Cy796ptGofSvC9tbTalrkoVBY/JjU5IpmuT9dPmQqx90i/MAYDkR2fZqyusUmeZ1Xe9eYn7isyuJnEJaa70oGKv0xWF5qxX/dGQcZ+Y3qXaRdEAtpPgLvW8fz+IQN+qn2QjaOXf8ko1IxUTxWWkH2NuTieCmMRPkAAAAUnn77HdnlLhs2Hr5p2hM730ZhEtMAAACAbKAU4PbpcefMUyvOmJNiX8xfybVz0DUVNq6D2CMap3gCBccqccmDAKrWDWt5LoGPdtH0kZom/AXFN5w+wyYmuoNwPY4oq1pgoDV9B/5ZCJnY2zYlsifdXH3y+ozItG2KoDVSmvlOvevN5rQ5XnXdAK9U8PM71nhSORdeJ5G+7GgAAACAAbhnQwYyranBL+CZTo4GL0myRx2Yglt/aRmMT7pAJ82IlCvpt4Amc7wvPQhwBruyX+f+M50F1PFnftasUuaLKHVUH5s1lPRL8hP6RzhNqwtGQoI16jw5bZeAFS67RN1tSC86uwq94MfVjXE+6vlxFVOnkpXB6dODRM6MEjQyp/QAAAAUO5OFdji2dMsW05NoK5EoYy7ZQBc="
			],
			"Peers": null,
			"HideStatusUpdates": false,
			"OTRAutoTearDown": true,
			"OTRAutoAppendTag": true,
			"OTRAutoStartSession": true,
			"AlwaysEncrypt": true,
			"ConnectAutomatically": false,
			"Certificates": [
				{
					"Subject": "jabber.otr.im",
					"Issuer": "Let's Encrypt Authority X3",
					"FingerprintHex": "540d81f9612eb581b7f68a8ced4e3aa8d820ede6c132e8f20257cbb1d46d282d",
					"FingerprintType": "SHA3-256"
				}
			]
		}
	],
	"Bell": false,
	"ConnectAutomatically": false,
	"Display": {
		"MergeAccounts": false,
		"ShowOnlyOnline": false,
		"HideFeedbackBar": true,
		"ShowOnlyConfirmed": false,
		"SortByStatus": false
	},
	"AdvancedOptions": false,
	"UniqueConfigurationID": "3061613738363365303763376365636164383561313037626536323038333232"
}
```

**Comment by olabiniV2** [comment] 2020-08-12 18:15
And just so I am completely clear, with this configuration, it will load the first account only?

**Comment by meme-lord** [comment] 2020-08-12 18:16
Sometimes it will load 2, and sometimes it will load 1. If there is 3 or more accounts in the config though it will never load more than 2.

**Comment by olabiniV2** [comment] 2020-08-12 18:17
OK, thank you. I will try to use this configuration file to see if I can reproduce the issue with the 3.11 release, and then get back to you.

**Comment by olabiniV2** [comment] 2020-08-17 15:57
OK, so testing 0.3.11 on a Linux machine with the above configuration file does not show the problem. I tried starting 10-20 times and everything looked fine. Next step is to try it out on Windows.

**Comment by olabiniV2** [comment] 2020-08-24 15:27
We have finally managed to reproduce the issue on Windows with the newest code as well. Hopefully that means we can identify the issue soon.
One clarifying question - are you using the encrypted configuration file, or un-encrypted?

**Comment by meme-lord** [comment] 2020-08-24 16:01
Unencrypted - the config I sent earlier is the contents of the accounts.json file.
Good job on reproducing it!

**Closed** 2020-08-27 17:55 UTC

**Comment by olabiniV2** [comment] 2020-08-27 17:57
Thanks for the information about this issue! Thanks to the work by @MauroVelasco and @rmendoza83 in figuring the cause for the issue. The fix has now been pushed and will be part of the next release of CoyIM, which will hopefully happen within a short amount of time.

**Comment by meme-lord** [comment] 2020-08-27 18:06
Great! Thanks for fixing this issue @olabiniV2 @rmendoza83 @MauroVelasco
