### ISSUE TITLE
Notify occupants when their room is destroyed (10.9)

### ISSUE THREAD

**Issue by Cris2760** [coyim/coyim#657] opened 2020-07-20 16:52 UTC
When you are an occupant in a room, and an owner destroys the room, you should be told about it. It's possible to get a reason from the destruction, and also an alternate venue (which is a room name), and an optional password for this new venue. All of this should be displayed in a nice way to the user. The room view should remain, but marked in some way so the user understand that the conversation view and the roster view won't be updated anymore.

**Note:** Please see the reference on https://xmpp.org/extensions/xep-0045.html

**Comment by olabiniV2** [comment] 2020-07-21 22:01
This is part of #271.

**Comment by Cris2760** [comment] 2020-10-02 21:22
This depends on #656

**Comment by sacurio** [comment] 2020-11-19 16:06
@olabiniV2 the issue is ready to be reviewed.

**Comment by olabiniV2** [comment] 2020-11-19 16:47
OK, I've added some comments to these commits. Putting it back in dev.

**Comment by peterpalau** [comment] 2020-11-20 16:17
Okay, @MauroVelasco, @peterpalau and @sacurio fixed all the pending comments and,now this issue is ready to be reviewed by @olabini.

**Comment by olabiniV2** [comment] 2020-11-23 21:01
OK, looks good to me.

**Comment by peterpalau** [comment] 2020-11-23 21:08
> OK, looks good to me.

Okay, since the user test are done, we are going to close this issue.

**Closed** 2020-11-23 21:09 UTC
Labels: Estimate - small, MUC, MUC - Room Owner Capabilities Functionality, Priority: Now, State: Test, blocked
